### ISSUE TITLE
Coupon codes dont seem to work

### ISSUE THREAD

**Issue by skysb** [jsbonso/aws-certified-solutions-architect-associate-practice-exam-reviewer#1]
Hi,

The coupon codes dont seem to work, would you mind emailing me the samplers?

**Comment by jsbonso** [comment]
Hi skysb, 

We have been giving away free samplers of our courses/ reviewer for over a year now and the promotion has been expired. Sadly, there were quite a lot of people who abused our free sampler and deliberately copied and sold them as their own. Hence, we decided to end the free sampler to avoid this from happening again. 

I have updated the coupon code for the premium version of my AWS reviewer. If you are not happy with the product, there is a 30-day, no-questions-asked, money-back guarantee.

Thank you and let's keep in touch!

**Comment by skysb** [comment]
any way we could be in touch?
________________________________

**Comment by jsbonso** [comment]
We can keep in touch in Linkedin, here's my profile: https://www.linkedin.com/in/jonbonso/
